server:
  port: 8080 #服务的端口号
spring:
  profiles:
    active: prod
eureka:
  instance:
    hostname: 106.14.140.93
  client:
    registerWithEureka: false   #表示是否将自己注册到Eureka Server，默认为true
    fetchRegistry: false     #表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  #设置与Eureka Server交互的地址
