version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  proxy:
    external: true
