env:
	docker stack deploy -c docker-compose-env.yml env

app:
	docker stack deploy -c docker-compose-app.yml app

nginx:
	docker stack deploy -c docker-compose-nginx.yml nginx

plain:
	docker stack deploy -c docker-compose-plain.yml plain
