server:
  port: 8090
spring:
  profiles:
    active: '@spring.profiles.active@'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NJU-SE3/OASIS-Service
          search-paths: /config
          default-label: dev
  application:
    name: config-server
eureka:
  port: 8761

