version: '2'

services:
  redis: # Redis缓存
    image: redis
    container_name: oasis-redis
    command: redis-server
    ports:
      - "6379:6379"
  rabbitmq:
    hostname: myrabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  mongodb:
    image: bitnami/mongodb:4.0
    container_name: oasis-mongo
    restart: always
    user: root
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=se

  neo4j:
    image: neo4j:3.0
    ports:
      - "7474:7474"