version: '3'

# wxj
# ES app
services:
#  oasis-paper:
#    image: 'registry.cn-shanghai.aliyuncs.com/caribou/oasis-paper'
#    container_name: oasis-paper
#    restart: always
#    networks:
#      - oasis
#    ports:
#      - "8080:8080"
  oasis-document:
    image: 'registry.cn-shanghai.aliyuncs.com/caribou/oasis-document'
    container_name: oasis-document
    restart: always
    ports:
      - "8081:8080"
    networks:
      - oasis

networks:
  oasis:
    external: true