version: '2'

# lfm
services:
  oasis-zuul:
    image: 'registry.cn-shanghai.aliyuncs.com/caribou/oasis-zuul'
    container_name: oasis-zuul
    restart: always
    ports:
      - "8081:8080"
    networks:
      - oasis
      - proxy
    environment:
      - VIRTUAL_HOST=api.oasi.top
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.oasi.top
      - LETSENCRYPT_EMAIL=1071956678@qq.com
networks:
  proxy:
    external: true
  oasis:
    driver: bridge