server:
  port: 8080
#配置eureka服务地址
eureka:
  port: 8080
  instance:
    hostname: oasis-eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

paper: oasis-paper:8080

zuul:
  host:
    #zuul配置
    max-per-route-connections: 50
    max-total-connections: 200
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  retryable: true
  routes:
    paper:
      path: /api/paper/**
      url: http://${paper}/
      serviceId: oasis-paper
  include-debug-header: true
