server:
  port: 8081

spring:
  # Profile 动态环境调整
  # mvn clean package -P<profile name>
  profiles:
    active: '@spring.profiles.active@'
  session:
    store-type: redis
  data:
    neo4j:
      uri: http://116.62.7.102:7474
