server:
  port: 8081

spring:
  # Profile 动态环境调整
  # mvn clean package -P<profile name>
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: oasis-document
  session:
    store-type: redis
spring.main.allow-bean-definition-overriding: true


eureka:
  port: 8761
  instance:
    hostname: 106.14.140.93
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# seconds
cache.default.expire-time: 120
cache.user.expire-time: 180
