server:
  port: 8080
spring:
  # Profile 动态环境调整
  # mvn clean package -P<profile name>
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: oasis-paper
spring.main.allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.oasispaper.model

eureka:
  port: 8761
  instance:
    hostname: 106.14.140.93
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/