server:
  port: 8080
eureka:
  port: 8761
spring:
  # Profile 动态环境调整
  # mvn clean package -P<profile name>
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: oasis-paper
spring.main.allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.oasispaper.model
