server:
  port: 8080
eureka:
  port: 8761
spring:
  # Profile 动态环境调整
  # mvn clean package -P<profile name>
  application:
    name: oasis-paper
  profiles:
    active: '@spring.profiles.active@'

spring.main.allow-bean-definition-overriding: true